plugins {
    id("com.android.application")
    // START: FlutterFire Configuration
    id("com.google.gms.google-services")
    id("com.google.firebase.crashlytics")
    // END: FlutterFire Configuration
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

android {
    namespace = "jp.example.sample"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    defaultConfig {
        // 各 Flavor の設定は flavorizr.gradle.kts で上書きされるため、ここはデフォルト値を設定
        applicationId = "jp.example.sample"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

flutter {
    source = "../.."
}

// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply(from = "flavorizr.gradle.kts")
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----

// 💡 ビルド時に現在の設定情報を出力するタスク
tasks.register("printAppConfig") {
    doLast {
        println("🚀 Android Build Config -> ApplicationId: ${android.defaultConfig.applicationId}, Namespace: ${android.namespace}")
    }
}

// ビルド開始前に実行
afterEvaluate {
    tasks.findByName("preBuild")?.dependsOn("printAppConfig")
}
